stages:
  - deploy

deploy:
  stage: deploy
  script:
    # Установка SSH-клиента (если ещё не установлен)
    - 'which ssh-agent || ( apt-get update -qq && apt-get install -y openssh-client git )'

    # Запуск агента
    - eval $(ssh-agent -s)

    # Создания .ssh directory
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Добавляем приватный ключ из переменной GitLab
    - echo "$SSH_PRIVATE" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519

    # Добавляем хост в known_hosts
    - mkdir -p ~/.ssh
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Выполняем команды на сервере
    - ssh -o StrictHostKeyChecking=yes admin@$SERVER_IP "
        cd /opt/delivery-uroven &&
        echo '🔁 Получаем последние изменения...' &&
        git pull origin main &&
        echo '🛠️ Пересобираем образы...' &&
        docker compose build --no-cache &&
        echo '🛑 Останавливаем контейнеры...' &&
         docker compose down &&
        echo '🚀 Запускаем сервисы...' &&
        docker compose up -d
      "
  only:
    - main
