services:
    delivery-api:
        build: .
        container_name: delivery-api
        restart: always
        env_file: .env
        environment:
            - NODE_ENV=production
            - LOG_DIR=/app/logs
            - LOG_FILE=app.log
            - LOG_LEVEL=INFO
        volumes:
            - ./logs:/app/logs
        networks:
            - traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.delivery-api.rule=Host(`delivery.uroven.pro`)
            - traefik.http.routers.delivery-api.entrypoints=websecure
            - traefik.http.routers.delivery-api.tls.certresolver=mytlschallenge
            - traefik.http.routers.delivery-api.tls=true
            - traefik.http.services.delivery-api.loadbalancer.server.port=3000

networks:
    traefik:
        external: true
        name: n8n_default
